name = "cf-workers-telegram-bot"
main = "packages/worker/dist/worker/src/worker.mjs"

workers_dev = true
compatibility_date = "2023-10-24"

build.command = "npm install && npm run build:worker"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "llama2"
database_id = "02cf6e8b-9f7e-46a9-9a95-dcc060d7c06d"

[[r2_buckets]]
binding = "R2"
bucket_name = "share"

[vars]
# SECRET_TELEGRAM_API_TOKEN = "test"